lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(int:JWT_TTL)%'

    set_cookies:
        bagage_token:
            lifetime: '%env(int:JWT_TTL)%'
            samesite: "lax" # "lax", "strict" ou "none"
            path: /
            domain: '%env(JWT_COOKIE_DOMAIN)%'
            secure: '%env(bool:JWT_COOKIE_SECURE)%'
            httpOnly: '%env(bool:JWT_COOKIE_HTTPONLY)%'

    token_extractors:
        cookie:
            enabled: true
            name: '%env(JWT_COOKIE_NAME)%'
        authorization_header:
            enabled: true
