monolog:
    channels:
        - deprecation # Les dépréciations sont isolées dans un canal dédié

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            # Handler principal : capture les erreurs HTTP 500 et plus
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
                buffer_size: 50

            # Groupe pour écrire à la fois dans un fichier local et sur stderr (docker logs)
            grouped:
                type: group
                members: [file, stderr]

            # Log complet (niveau debug) vers un fichier persistant (lecture via docker exec)
            file:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

            # Log des erreurs vers STDERR pour CapRover / Docker logs
            stderr:
                type: stream
                path: php://stderr
                level: error
                formatter: monolog.formatter.json

            # Console (utile pour commandes cron ou messenger)
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            # Canal spécifique pour les dépréciations PHP/Symfony
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
