parameters:
    app.uploads_dir: '%env(UPLOADS_DIR)%'
    app.max_file_size: '%env(int:MAX_FILE_SIZE)%'
    app.frontend_url: '%env(FRONTEND_URL)%'

    # OAuth Google
    google.client_id: '%env(GOOGLE_CLIENT_ID)%'
    google.client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    google.redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'

    # OAuth Facebook
    facebook.app_id: '%env(FACEBOOK_APP_ID)%'
    facebook.app_secret: '%env(FACEBOOK_APP_SECRET)%'
    facebook.redirect_uri: '%env(FACEBOOK_REDIRECT_URI)%'

    app.default_currency: '%env(DEFAULT_CURRENCY)%'
    app.exchange_rate_api_key: '%env(EXCHANGE_RATE_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # EmailService
    App\Service\EmailService:
        arguments:
            $frontendUrl: '%app.frontend_url%'

    App\Service\CurrencyService:
        arguments:
            $exchangeRateApiKey: '%app.exchange_rate_api_key%'
            $defaultCurrency: '%app.default_currency%'

    # ==================== CONFIGURATION TWILIO ====================
    App\Service\TwilioService:
        arguments:
            $logger: '@logger'
            $twilioAccountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $twilioAuthToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'

    # GoogleAuthService
    App\Service\OAuth\GoogleAuthService:
        arguments:
            $googleClientId: '%google.client_id%'
            $googleClientSecret: '%google.client_secret%'
            $googleRedirectUri: '%google.redirect_uri%'

    # FacebookAuthService
    App\Service\OAuth\FacebookAuthService:
        arguments:
            $facebookAppId: '%facebook.app_id%'
            $facebookAppSecret: '%facebook.app_secret%'
            $facebookRedirectUri: '%facebook.redirect_uri%'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # JWT Cookie Authenticator
    App\Security\JWTCookieAuthenticator:
        parent: lexik_jwt_authentication.security.jwt_authenticator

    # JWT Event Listener
    App\EventListener\JWTListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailure }

    # Configuration de l'ExceptionListener
    App\EventListener\ExceptionListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    App\EventListener\BannedUserListener:
        tags:
        - { name: kernel.event_listener, event: kernel.request, priority: 10 }
